### ISSUE TITLE
Two versions of the dashboard are live

### ISSUE THREAD

**Issue by statnmap** [r-hub/cransays#35]
It seems there are two versions of the dashboard. One is updated, but not the other. 

Correct: https://lockedata.github.io/cransays/articles/dashboard.html

Not updated ? https://itsalocke.com/cransays/articles/dashboard

**Comment by maelle** [comment]
@stephlocke

**Comment by Bisaloo** [comment]
- https://lockedata.github.io/cransays/articles/dashboard.html now redirects to https://r-hub.github.io/cransays/articles/dashboard.html (the new canonical page for the dashboard)

- https://itsalocke.com/cransays/articles/dashboard now `404`s but I think we removed all links to it

We should now be fine. I'm therefore closing this issue. Please let me know if I forgot something.

**Comment by stephlocke** [comment]
I've pushed a redirect for the 404 url just in case it got indexed somewhere 👍
