### ISSUE TITLE
Update GitHub PAT

### ISSUE THREAD

**Issue by maelle** [r-hub/cransays#44]

**Comment by llrs** [comment]
Given the change on the repo, maybe it is worth updating the github action: now there is no need to provide a generated Github Pat if I recall correctly, actions have a dedicate PAT already available.

Update links to the website (https://r-hub.github.io/cransays/articles/dashboard.html).
Maybe ask if the old site (https://lockedata.github.io/cransays/articles/dashboard.html) can be redirected to the new one?

**Comment by maelle** [comment]
@llrs thank you! @stephlocke set up a redirect (thanks Steph!)

**Comment by llrs** [comment]
Many thanks to you for this great service to the community!
