### ISSUE TITLE
Confusing description of category?

### ISSUE THREAD

**Issue by llrs** [r-hub/cransays#59]
Today on the r-pkg-devel mailing list there was a question about the meaning of the folders/labels

Reference email from UweLigges: https://stat.ethz.ch/pipermail/r-package-devel/2022q2/008084.html (and see the whole thread)

And there is an email from Ben Bolker highlighting the difference with foghorn https://github.com/fmichonneau/foghorn/issues/42

**Comment by bbolker** [comment]
duplicate of #29, working on it ...
