### ISSUE TITLE
Alternative approach

### ISSUE THREAD

**Issue by nx10** [r-hub/cransays#63]
Hi,

great work on the dashboard.
I built a similar website, but with a different approach:

* Tiny Rust server backend that lazily fetches data from the incoming FTP and caches it in memory (currently for 10 minutes)
* Svelte Frontend on GitHub Pages with auto-reload, search, and let's you track individual packages.

Website:
https://nx10.github.io/cransubs/

Repos:
https://github.com/nx10/cransubs
https://github.com/nx10/cransubs-server

It would be great to hear what you think.
Feel free to close this issue anytime.

**Comment by Bisaloo** [comment]
Hi @nx10 :wave:, thanks for your message!

Your website looks nice and it seems like a very solid technical contribution! We particularly like the high-refresh frequency and the laziness. This is very elegant and seems quite efficient!

I will submit a PR soon to mention your website in the [related projects](https://github.com/r-hub/cransays#related-work) and tag you there so you can review my explanation of the differences and make sure I don't say anything wrong.

**Comment by nx10** [comment]
Thank you for the nice feedback and PR @Bisaloo !

The primary issue with my approach is the need for a dedicated server. I am currently hosting it on the free tier of fly.io, but I don't know how this would hold up if it got popular in any way. If anyone is interested in hosting it they can consider all the code I wrote free of any copyright, I will add either MIT or BSD at a later date.
